sudo: false

# Branch blocklist
branches:
  except:
  - master


language: node_js
node_js: "13.6.0"

install: sh install-dependencies.sh

cache:
   yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
  - stage: "Deploy Windows & Mac"
      if: tag IS present
      os: osx
      osx_image: xcode10.2
      script:
        - newVersion=$(git describe --abbrev=0)
        - yarn version $newVersion
        - yarn run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: "Deploy Linux"
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - newVersion=$(git describe --abbrev=0)
        - yarn version $newVersion
        - yarn run release

after_success:
  - sh push-updates-with-travis-build.sh
